# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './skin/account.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_account(object):
    def setupUi(self, account):
        account.setObjectName("account")
        account.resize(553, 362)
        self.gridLayout_3 = QtWidgets.QGridLayout(account)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(account)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_pass = QtWidgets.QLineEdit(account)
        self.lineEdit_pass.setMinimumSize(QtCore.QSize(157, 21))
        self.lineEdit_pass.setMaximumSize(QtCore.QSize(20000, 21))
        self.lineEdit_pass.setText("")
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.gridLayout_2.addWidget(self.lineEdit_pass, 0, 1, 1, 1)
        self.pushButton_genAddress = QtWidgets.QPushButton(account)
        self.pushButton_genAddress.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_genAddress.sizePolicy().hasHeightForWidth())
        self.pushButton_genAddress.setSizePolicy(sizePolicy)
        self.pushButton_genAddress.setMinimumSize(QtCore.QSize(94, 32))
        self.pushButton_genAddress.setMaximumSize(QtCore.QSize(94, 32))
        self.pushButton_genAddress.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_genAddress.setObjectName("pushButton_genAddress")
        self.gridLayout_2.addWidget(self.pushButton_genAddress, 0, 2, 1, 1)
        self.pushButton_genPass = QtWidgets.QPushButton(account)
        self.pushButton_genPass.setMinimumSize(QtCore.QSize(94, 32))
        self.pushButton_genPass.setMaximumSize(QtCore.QSize(94, 32))
        self.pushButton_genPass.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_genPass.setObjectName("pushButton_genPass")
        self.gridLayout_2.addWidget(self.pushButton_genPass, 0, 3, 1, 1)
        self.pushButton_copyPass = QtWidgets.QPushButton(account)
        self.pushButton_copyPass.setEnabled(True)
        self.pushButton_copyPass.setMinimumSize(QtCore.QSize(94, 32))
        self.pushButton_copyPass.setMaximumSize(QtCore.QSize(94, 32))
        self.pushButton_copyPass.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_copyPass.setObjectName("pushButton_copyPass")
        self.gridLayout_2.addWidget(self.pushButton_copyPass, 0, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(account)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_address = QtWidgets.QLabel(account)
        self.label_address.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_address.setAutoFillBackground(True)
        self.label_address.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_address.setText("")
        self.label_address.setObjectName("label_address")
        self.gridLayout_2.addWidget(self.label_address, 1, 1, 1, 4)
        self.pushButton_copyAddress = QtWidgets.QPushButton(account)
        self.pushButton_copyAddress.setEnabled(False)
        self.pushButton_copyAddress.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_copyAddress.setObjectName("pushButton_copyAddress")
        self.gridLayout_2.addWidget(self.pushButton_copyAddress, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(account)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_pubKey = QtWidgets.QLabel(account)
        self.label_pubKey.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_pubKey.setAutoFillBackground(True)
        self.label_pubKey.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_pubKey.setText("")
        self.label_pubKey.setObjectName("label_pubKey")
        self.gridLayout_2.addWidget(self.label_pubKey, 2, 1, 1, 4)
        self.pushButton_copyPubKey = QtWidgets.QPushButton(account)
        self.pushButton_copyPubKey.setEnabled(False)
        self.pushButton_copyPubKey.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_copyPubKey.setObjectName("pushButton_copyPubKey")
        self.gridLayout_2.addWidget(self.pushButton_copyPubKey, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(account)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_priKey = QtWidgets.QLabel(account)
        self.label_priKey.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_priKey.setAutoFillBackground(True)
        self.label_priKey.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_priKey.setText("")
        self.label_priKey.setObjectName("label_priKey")
        self.gridLayout_2.addWidget(self.label_priKey, 3, 1, 1, 4)
        self.pushButton_copyPrivateKey = QtWidgets.QPushButton(account)
        self.pushButton_copyPrivateKey.setEnabled(False)
        self.pushButton_copyPrivateKey.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_copyPrivateKey.setObjectName("pushButton_copyPrivateKey")
        self.gridLayout_2.addWidget(self.pushButton_copyPrivateKey, 3, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(account)
        self.label_5.setMinimumSize(QtCore.QSize(51, 16))
        self.label_5.setMaximumSize(QtCore.QSize(51, 61))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.textBrowser_keyStore = QtWidgets.QTextBrowser(account)
        self.textBrowser_keyStore.setObjectName("textBrowser_keyStore")
        self.gridLayout.addWidget(self.textBrowser_keyStore, 0, 1, 3, 1)
        self.pushButton_copyKeyStore = QtWidgets.QPushButton(account)
        self.pushButton_copyKeyStore.setEnabled(False)
        self.pushButton_copyKeyStore.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_copyKeyStore.setObjectName("pushButton_copyKeyStore")
        self.gridLayout.addWidget(self.pushButton_copyKeyStore, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 2, 1)
        self.pushButton_exportKeyStore = QtWidgets.QPushButton(account)
        self.pushButton_exportKeyStore.setEnabled(False)
        self.pushButton_exportKeyStore.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_exportKeyStore.setObjectName("pushButton_exportKeyStore")
        self.gridLayout.addWidget(self.pushButton_exportKeyStore, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(28, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(account)
        QtCore.QMetaObject.connectSlotsByName(account)

    def retranslateUi(self, account):
        _translate = QtCore.QCoreApplication.translate
        account.setWindowTitle(_translate("account", "创建账号"))
        self.label.setText(_translate("account", "密码"))
        self.pushButton_genAddress.setText(_translate("account", "创建地址"))
        self.pushButton_genPass.setText(_translate("account", "生成密码"))
        self.pushButton_copyPass.setText(_translate("account", "复制密码"))
        self.label_2.setText(_translate("account", "地址"))
        self.pushButton_copyAddress.setText(_translate("account", "复制"))
        self.label_3.setText(_translate("account", "公钥"))
        self.pushButton_copyPubKey.setText(_translate("account", "复制"))
        self.label_4.setText(_translate("account", "私钥"))
        self.pushButton_copyPrivateKey.setText(_translate("account", "复制"))
        self.label_5.setText(_translate("account", "KeyStoe"))
        self.pushButton_copyKeyStore.setText(_translate("account", "复制"))
        self.pushButton_exportKeyStore.setText(_translate("account", "导出"))

