# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './skin/permission.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_permission(object):
    def setupUi(self, permission):
        permission.setObjectName("permission")
        permission.resize(441, 186)
        self.gridLayout_2 = QtWidgets.QGridLayout(permission)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(permission)
        self.label.setMinimumSize(QtCore.QSize(81, 21))
        self.label.setMaximumSize(QtCore.QSize(81, 21))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(permission)
        self.lineEdit.setMinimumSize(QtCore.QSize(321, 21))
        self.lineEdit.setMaximumSize(QtCore.QSize(365, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 6)
        self.label_2 = QtWidgets.QLabel(permission)
        self.label_2.setMinimumSize(QtCore.QSize(81, 21))
        self.label_2.setMaximumSize(QtCore.QSize(81, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(permission)
        self.label_7.setMinimumSize(QtCore.QSize(81, 21))
        self.label_7.setMaximumSize(QtCore.QSize(81, 21))
        self.label_7.setAutoFillBackground(True)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 3)
        self.label_4 = QtWidgets.QLabel(permission)
        self.label_4.setMinimumSize(QtCore.QSize(81, 21))
        self.label_4.setMaximumSize(QtCore.QSize(81, 21))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(permission)
        self.label_8.setMinimumSize(QtCore.QSize(81, 21))
        self.label_8.setMaximumSize(QtCore.QSize(81, 21))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 2)
        self.pushButton = QtWidgets.QPushButton(permission)
        self.pushButton.setMinimumSize(QtCore.QSize(91, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(91, 32))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(permission)
        self.label_6.setMinimumSize(QtCore.QSize(0, 21))
        self.label_6.setMaximumSize(QtCore.QSize(81, 21))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(permission)
        self.checkBox.setMinimumSize(QtCore.QSize(77, 21))
        self.checkBox.setMaximumSize(QtCore.QSize(77, 21))
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(permission)
        self.checkBox_2.setMinimumSize(QtCore.QSize(77, 21))
        self.checkBox_2.setMaximumSize(QtCore.QSize(77, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 3, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 5, 1, 2)
        self.label_9 = QtWidgets.QLabel(permission)
        self.label_9.setMinimumSize(QtCore.QSize(0, 21))
        self.label_9.setMaximumSize(QtCore.QSize(81, 21))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(permission)
        self.spinBox.setMinimumSize(QtCore.QSize(41, 21))
        self.spinBox.setMaximumSize(QtCore.QSize(41, 21))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 4)
        self.pushButton_2 = QtWidgets.QPushButton(permission)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(91, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(91, 32))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(permission)
        QtCore.QMetaObject.connectSlotsByName(permission)

    def retranslateUi(self, permission):
        _translate = QtCore.QCoreApplication.translate
        permission.setWindowTitle(_translate("permission", "权限操作"))
        self.label.setText(_translate("permission", "地址"))
        self.label_2.setText(_translate("permission", "创建账户"))
        self.label_4.setText(_translate("permission", "发送交易"))
        self.pushButton.setText(_translate("permission", "查询权限"))
        self.label_6.setText(_translate("permission", "权限集"))
        self.checkBox.setText(_translate("permission", "创建账户"))
        self.checkBox_2.setText(_translate("permission", "发送交易"))
        self.label_9.setText(_translate("permission", "临时发送交易"))
        self.pushButton_2.setText(_translate("permission", "变更权限"))

