# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './skin/tradeinfo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tradeinfo(object):
    def setupUi(self, tradeinfo):
        tradeinfo.setObjectName("tradeinfo")
        tradeinfo.resize(662, 368)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/tools.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tradeinfo.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(tradeinfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(tradeinfo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_txHash = QtWidgets.QLineEdit(tradeinfo)
        self.lineEdit_txHash.setMinimumSize(QtCore.QSize(497, 0))
        self.lineEdit_txHash.setText("")
        self.lineEdit_txHash.setObjectName("lineEdit_txHash")
        self.gridLayout.addWidget(self.lineEdit_txHash, 0, 1, 1, 1)
        self.pushButtonSearch = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch.setMouseTracking(False)
        self.pushButtonSearch.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch.setAcceptDrops(False)
        self.pushButtonSearch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch.setAutoFillBackground(False)
        self.pushButtonSearch.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.gridLayout.addWidget(self.pushButtonSearch, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(tradeinfo)
        self.label_5.setEnabled(True)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setProperty("tabletTracking", False)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_txHash = QtWidgets.QLabel(tradeinfo)
        self.label_txHash.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_txHash.setAutoFillBackground(True)
        self.label_txHash.setText("")
        self.label_txHash.setObjectName("label_txHash")
        self.gridLayout.addWidget(self.label_txHash, 1, 1, 1, 1)
        self.pushButtonSearch_txhash = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_txhash.setEnabled(False)
        self.pushButtonSearch_txhash.setMouseTracking(False)
        self.pushButtonSearch_txhash.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonSearch_txhash.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_txhash.setAcceptDrops(False)
        self.pushButtonSearch_txhash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_txhash.setAutoFillBackground(False)
        self.pushButtonSearch_txhash.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_txhash.setObjectName("pushButtonSearch_txhash")
        self.gridLayout.addWidget(self.pushButtonSearch_txhash, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(tradeinfo)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(tradeinfo)
        self.label_status.setMinimumSize(QtCore.QSize(45, 0))
        self.label_status.setMaximumSize(QtCore.QSize(45, 19))
        self.label_status.setAutoFillBackground(True)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(tradeinfo)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_blockTxHash = QtWidgets.QLabel(tradeinfo)
        self.label_blockTxHash.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_blockTxHash.setAutoFillBackground(True)
        self.label_blockTxHash.setText("")
        self.label_blockTxHash.setObjectName("label_blockTxHash")
        self.gridLayout.addWidget(self.label_blockTxHash, 3, 1, 1, 1)
        self.pushButtonSearch_blockTxHash = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_blockTxHash.setEnabled(False)
        self.pushButtonSearch_blockTxHash.setMouseTracking(False)
        self.pushButtonSearch_blockTxHash.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_blockTxHash.setAcceptDrops(False)
        self.pushButtonSearch_blockTxHash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_blockTxHash.setAutoFillBackground(False)
        self.pushButtonSearch_blockTxHash.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_blockTxHash.setObjectName("pushButtonSearch_blockTxHash")
        self.gridLayout.addWidget(self.pushButtonSearch_blockTxHash, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(tradeinfo)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_from = QtWidgets.QLabel(tradeinfo)
        self.label_from.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_from.setAutoFillBackground(True)
        self.label_from.setText("")
        self.label_from.setObjectName("label_from")
        self.gridLayout.addWidget(self.label_from, 4, 1, 1, 1)
        self.pushButtonSearch_from = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_from.setEnabled(False)
        self.pushButtonSearch_from.setMouseTracking(False)
        self.pushButtonSearch_from.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_from.setAcceptDrops(False)
        self.pushButtonSearch_from.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_from.setAutoFillBackground(False)
        self.pushButtonSearch_from.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_from.setObjectName("pushButtonSearch_from")
        self.gridLayout.addWidget(self.pushButtonSearch_from, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(tradeinfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_to = QtWidgets.QLabel(tradeinfo)
        self.label_to.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_to.setAutoFillBackground(True)
        self.label_to.setText("")
        self.label_to.setObjectName("label_to")
        self.gridLayout.addWidget(self.label_to, 5, 1, 1, 1)
        self.pushButtonSearch_to = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_to.setEnabled(False)
        self.pushButtonSearch_to.setMouseTracking(False)
        self.pushButtonSearch_to.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_to.setAcceptDrops(False)
        self.pushButtonSearch_to.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_to.setAutoFillBackground(False)
        self.pushButtonSearch_to.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_to.setObjectName("pushButtonSearch_to")
        self.gridLayout.addWidget(self.pushButtonSearch_to, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(tradeinfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_nonce = QtWidgets.QLabel(tradeinfo)
        self.label_nonce.setMinimumSize(QtCore.QSize(100, 0))
        self.label_nonce.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_nonce.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_nonce.setAutoFillBackground(True)
        self.label_nonce.setText("")
        self.label_nonce.setObjectName("label_nonce")
        self.gridLayout.addWidget(self.label_nonce, 6, 1, 1, 1)
        self.pushButtonSearch_nonce = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_nonce.setEnabled(False)
        self.pushButtonSearch_nonce.setMouseTracking(False)
        self.pushButtonSearch_nonce.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_nonce.setAcceptDrops(False)
        self.pushButtonSearch_nonce.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_nonce.setAutoFillBackground(False)
        self.pushButtonSearch_nonce.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_nonce.setObjectName("pushButtonSearch_nonce")
        self.gridLayout.addWidget(self.pushButtonSearch_nonce, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(tradeinfo)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.textBrowser_data = QtWidgets.QTextBrowser(tradeinfo)
        self.textBrowser_data.setObjectName("textBrowser_data")
        self.gridLayout.addWidget(self.textBrowser_data, 7, 1, 2, 1)
        self.pushButtonSearch_data = QtWidgets.QPushButton(tradeinfo)
        self.pushButtonSearch_data.setEnabled(False)
        self.pushButtonSearch_data.setMouseTracking(False)
        self.pushButtonSearch_data.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonSearch_data.setAcceptDrops(False)
        self.pushButtonSearch_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch_data.setAutoFillBackground(False)
        self.pushButtonSearch_data.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButtonSearch_data.setObjectName("pushButtonSearch_data")
        self.gridLayout.addWidget(self.pushButtonSearch_data, 8, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(tradeinfo)
        QtCore.QMetaObject.connectSlotsByName(tradeinfo)

    def retranslateUi(self, tradeinfo):
        _translate = QtCore.QCoreApplication.translate
        tradeinfo.setWindowTitle(_translate("tradeinfo", "交易查询"))
        self.label_2.setText(_translate("tradeinfo", "TxHash"))
        self.pushButtonSearch.setText(_translate("tradeinfo", "查询"))
        self.label_5.setText(_translate("tradeinfo", "交易哈希"))
        self.pushButtonSearch_txhash.setText(_translate("tradeinfo", "复制"))
        self.label_6.setText(_translate("tradeinfo", "交易状态"))
        self.label_7.setText(_translate("tradeinfo", "区块哈希"))
        self.pushButtonSearch_blockTxHash.setText(_translate("tradeinfo", "复制"))
        self.label_8.setText(_translate("tradeinfo", "From"))
        self.pushButtonSearch_from.setText(_translate("tradeinfo", "复制"))
        self.label_9.setText(_translate("tradeinfo", "To"))
        self.pushButtonSearch_to.setText(_translate("tradeinfo", "复制"))
        self.label_10.setText(_translate("tradeinfo", "Nonce"))
        self.pushButtonSearch_nonce.setText(_translate("tradeinfo", "复制"))
        self.label_11.setText(_translate("tradeinfo", "Data"))
        self.pushButtonSearch_data.setText(_translate("tradeinfo", "复制"))

import icons_rc
