# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './skin/yglian.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_yglian(object):
    def setupUi(self, yglian):
        yglian.setObjectName("yglian")
        yglian.resize(599, 457)
        self.layoutWidget = QtWidgets.QWidget(yglian)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 561, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditTxHash = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTxHash.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditTxHash.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditTxHash.setText("")
        self.lineEditTxHash.setObjectName("lineEditTxHash")
        self.horizontalLayout_2.addWidget(self.lineEditTxHash)
        self.pushButtonSearch = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout_2.addWidget(self.pushButtonSearch)
        self.widget = QtWidgets.QWidget(yglian)
        self.widget.setGeometry(QtCore.QRect(20, 20, 561, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditWeb3No = QtWidgets.QLineEdit(self.widget)
        self.lineEditWeb3No.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditWeb3No.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditWeb3No.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditWeb3No.setObjectName("lineEditWeb3No")
        self.horizontalLayout.addWidget(self.lineEditWeb3No)
        self.pushButtonConnect = QtWidgets.QPushButton(self.widget)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout.addWidget(self.pushButtonConnect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.textBrowserBlockNumber = QtWidgets.QTextBrowser(self.widget)
        self.textBrowserBlockNumber.setEnabled(True)
        self.textBrowserBlockNumber.setMinimumSize(QtCore.QSize(100, 21))
        self.textBrowserBlockNumber.setMaximumSize(QtCore.QSize(100, 21))
        self.textBrowserBlockNumber.setObjectName("textBrowserBlockNumber")
        self.horizontalLayout.addWidget(self.textBrowserBlockNumber)
        self.widget1 = QtWidgets.QWidget(yglian)
        self.widget1.setGeometry(QtCore.QRect(20, 100, 562, 338))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setEnabled(True)
        self.label_5.setTabletTracking(False)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.textBrowserTxHash = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserTxHash.setEnabled(True)
        self.textBrowserTxHash.setMinimumSize(QtCore.QSize(500, 21))
        self.textBrowserTxHash.setMaximumSize(QtCore.QSize(500, 21))
        self.textBrowserTxHash.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserTxHash.setObjectName("textBrowserTxHash")
        self.gridLayout.addWidget(self.textBrowserTxHash, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.textBrowserStatus = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserStatus.setEnabled(True)
        self.textBrowserStatus.setMinimumSize(QtCore.QSize(54, 21))
        self.textBrowserStatus.setMaximumSize(QtCore.QSize(54, 21))
        self.textBrowserStatus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserStatus.setObjectName("textBrowserStatus")
        self.gridLayout.addWidget(self.textBrowserStatus, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.textBrowserBlockHash = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserBlockHash.setEnabled(True)
        self.textBrowserBlockHash.setMinimumSize(QtCore.QSize(500, 21))
        self.textBrowserBlockHash.setMaximumSize(QtCore.QSize(54, 21))
        self.textBrowserBlockHash.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserBlockHash.setObjectName("textBrowserBlockHash")
        self.gridLayout.addWidget(self.textBrowserBlockHash, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.textBrowserForm = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserForm.setEnabled(True)
        self.textBrowserForm.setMinimumSize(QtCore.QSize(500, 21))
        self.textBrowserForm.setMaximumSize(QtCore.QSize(500, 21))
        self.textBrowserForm.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserForm.setObjectName("textBrowserForm")
        self.gridLayout.addWidget(self.textBrowserForm, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.textBrowserBlocKTo = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserBlocKTo.setEnabled(True)
        self.textBrowserBlocKTo.setMinimumSize(QtCore.QSize(500, 21))
        self.textBrowserBlocKTo.setMaximumSize(QtCore.QSize(54, 21))
        self.textBrowserBlocKTo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserBlocKTo.setObjectName("textBrowserBlocKTo")
        self.gridLayout.addWidget(self.textBrowserBlocKTo, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.textBrowserNonce = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserNonce.setEnabled(True)
        self.textBrowserNonce.setMinimumSize(QtCore.QSize(54, 21))
        self.textBrowserNonce.setMaximumSize(QtCore.QSize(54, 21))
        self.textBrowserNonce.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserNonce.setObjectName("textBrowserNonce")
        self.gridLayout.addWidget(self.textBrowserNonce, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.textBrowserData = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowserData.setEnabled(True)
        self.textBrowserData.setMinimumSize(QtCore.QSize(500, 150))
        self.textBrowserData.setMaximumSize(QtCore.QSize(500, 150))
        self.textBrowserData.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowserData.setObjectName("textBrowserData")
        self.gridLayout.addWidget(self.textBrowserData, 6, 1, 1, 1)

        self.retranslateUi(yglian)
        QtCore.QMetaObject.connectSlotsByName(yglian)

    def retranslateUi(self, yglian):
        _translate = QtCore.QCoreApplication.translate
        yglian.setWindowTitle(_translate("yglian", "阳光链调试工具"))
        self.label_2.setText(_translate("yglian", "TxHash"))
        self.pushButtonSearch.setText(_translate("yglian", "查询"))
        self.label.setText(_translate("yglian", "web3No"))
        self.lineEditWeb3No.setText(_translate("yglian", "https://web3.yglian.com"))
        self.pushButtonConnect.setText(_translate("yglian", "连接"))
        self.label_3.setText(_translate("yglian", "区块高度"))
        self.label_5.setText(_translate("yglian", "交易哈希"))
        self.label_6.setText(_translate("yglian", "交易状态"))
        self.label_7.setText(_translate("yglian", "区块哈希"))
        self.label_8.setText(_translate("yglian", "From"))
        self.label_9.setText(_translate("yglian", "To"))
        self.label_10.setText(_translate("yglian", "Nonce"))
        self.label_11.setText(_translate("yglian", "Data"))

